<?php

namespace AppBundle\Repository;

/**
 * ProjectsTechnologiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsTechnologiesRepository extends \Doctrine\ORM\EntityRepository
{
}
