<?php

namespace AppBundle\Repository;

/**
 * DirectoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
