<?php

namespace AppBundle\Repository;

/**
 * LangsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangsRepository extends \Doctrine\ORM\EntityRepository
{
}
